### ISSUE TITLE
It is possible to use it as a SQLite serializator?

### ISSUE THREAD

**Issue by JCKodel** [FlutterDevTools/simple_json#1]
JSON is ok to remote APIs, but it would be awesome if we could customize the serialization process to make it compatible with SQLite.

For instance, SQLite doesn't have bool, so we usually write 0 or 1 (false or true). Also, it does not have DateTime support, so we usually write the UTC ISO string and read the local time. Enums are also written as number.

Is there any way to customize these options in simple_json?

**Comment by D10100111001** [comment]
Thanks for the feedback. I have resolved this issue with the latest update and version (0.2.2). Let me know if that works for your needs.

Please refer to the [advanced example](../blob/master/example/lib/main.dart) for an example of usage.
