### ISSUE TITLE
Code generation fails when other code generators are used

### ISSUE THREAD

**Issue by jhoogstraat** [FlutterDevTools/simple_json#3]
I am using Flutter 1.17.4 stable.

When using other code generators like freezed, simple_json will fail, because the *.freezed.dart files are not Dart libraries.

build_runner logs:
> [SEVERE] simple_json:simple_json on lib/$lib$ (cached):
>
> Asset [App|lib/core/interfaces/scan_session_event.freezed.dart] is not a Dart library. It may be a part file or a file without Dart source code.

**Comment by D10100111001** [comment]
That specific error regarding the generated files has been fixed with the latest version (0.3.5). 

Not sure how integrating other generators like `freezed` will work though.

Feel free to open another issue if you have any ideas regarding this. Also, PRs are welcome.
