### ISSUE TITLE
Error in code generation for enum in parent class   

### ISSUE THREAD

**Issue by rsbichkar** [FlutterDevTools/simple_json#6]
The following (partial) code in flutter gives error:  
    Converting object to an encodable object failed: Instance of 'GenderType'
`
import 'package:simple_json_mapper/simple_json_mapper.dart';
import 'mapper.g.dart' as mapper;

void main() {
  mapper.init();
  runApp(MyApp());
}

enum GenderType { Male, Female, Other }

@JObj()
class Person {
  Person({this.name, this.age, this.gender});

  String name;
  int age;
  @JEnumProp(serializationType: SerializationType.Value)
  GenderType gender;
}

@JObj()
class Student extends Person {
  Student({name, age, gender, this.clas, this.rollno})
      : super(name: name, age: age, gender: gender);

  String clas;
  int rollno;
}

`

**Comment by D10100111001** [comment]
You need to specify the types of the fields in the Student class. Here is a working example with the null safety version of dart.

```dart
enum GenderType { Male, Female, Other }

@JObj()
class Person {
  Person({required this.name, required this.age, required this.gender});

  String name;
  int age;
  @JEnumProp(serializationType: SerializationType.Value)
  GenderType gender;
}

@JObj()
class Student extends Person {
  Student(
      {required String name,
      required int age,
      required GenderType gender,
      required this.clas,
      required this.rollno})
      : super(name: name, age: age, gender: gender);

  String clas;
  int rollno;
}

```
