### ISSUE TITLE
build_runner >=1.11.2 depends on glob ^2.0.0, simple_json ^1.2.2 is incompatible with build_runner 

### ISSUE THREAD

**Issue by sgehrman** [FlutterDevTools/simple_json#7]
And because build_runner >=1.11.2 depends on glob ^2.0.0, simple_json ^1.2.2 is incompatible with build_runner >=1.11.2.
So, because interview_dvx depends on both build_runner ^1.11.5 and simple_json ^1.2.2, version solving failed.

**Comment by D10100111001** [comment]
The package has been updated for null safety. Let me know if this is still an issue.
