### ISSUE TITLE
update packages

### ISSUE THREAD

**Issue by sgehrman** [FlutterDevTools/simple_json#8]
Because simple_json >=1.2.0 depends on build_resolvers ^1.5.1 and build_resolvers >=1.5.4 depends on analyzer ^1.0.0, simple_json >=1.2.0 requires analyzer ^1.0.0 or build_resolvers >=1.5.1 <1.5.4.
And because build_resolvers >=1.4.4 <1.5.4 depends on analyzer >=0.40.1 <0.42.0 and simple_json >=1.1.8 depends on analyzer >=0.37.0 <0.41.1, simple_json >=1.2.0 requires analyzer >=0.40.1 <0.41.1.
And because analyzer >=0.39.5 <0.41.2 depends on crypto ^2.0.0 and every version of flutter_shared from path depends on crypto ^3.0.0, simple_json >=1.2.0 is incompatible with flutter_shared from path.
So, because interview_dvx depends on both flutter_shared from path and simple_json ^1.2.2, version solving failed.

**Comment by D10100111001** [comment]
The package has been updated for null safety. Let me know if this is still an issue.
